In [48]:
import numpy as np


"""
Argument:
    A (np.array): (batch_size, in_channels, input_size)
    W (out_channels, in_channels, kernel_size)
Return:
    Z (np.array): (batch_size, out_channels, output_size)
"""
A = np.ones((2, 3, 7))
W = np.ones((2, 3, 2))
Z = np.ones((A.shape[0], W.shape[0], A.shape[2] - W.shape[2] + 1))
for i in range(A.shape[0]):
    for j in range(Z.shape[2]):
        tmp = A[i, ..., j:j + W.shape[2]]
        Z[i,...,j] = np.tensordot(tmp, W, axes = ([0, 1],[1, 2])).shape
print(Z)        


[[[2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]]]


In [47]:
print(Z+1)

[[[3. 3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3. 3.]]

 [[3. 3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3. 3.]]]
